# Generated by Django 5.1.4 on 2025-01-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mat_number', models.CharField(max_length=11)),
                ('departmant', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('blood_group', models.CharField(max_length=5)),
                ('passport', models.ImageField(upload_to='photos/')),
                ('signature', models.ImageField(upload_to='signature/')),
            ],
        ),
    ]
