# Generated by Django 5.1.4 on 2025-01-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idcard',
            old_name='departmant',
            new_name='department',
        ),
    ]
