# Generated by Django 5.1.4 on 2025-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_rename_departmant_idcard_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idcard',
            options={'verbose_name': 'Student Detail'},
        ),
        migrations.AlterField(
            model_name='idcard',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7),
        ),
    ]
